create table if not exists public.farmer_profiles (
  id bigint generated by default as identity primary key,
  farmer_id text unique not null,
  name text not null,
  field_group text not null,
  logbook_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.field_polygons (
  id bigint generated by default as identity primary key,
  farmer_id text not null references public.farmer_profiles(farmer_id) on delete cascade,
  farmer_name text not null,
  field_group text not null,
  area_ha numeric not null default 0,
  latlngs jsonb not null,
  logbook_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.farmer_profiles
add column if not exists logbook_data jsonb not null default '{}'::jsonb;

alter table public.field_polygons
add column if not exists logbook_data jsonb not null default '{}'::jsonb;

alter table public.farmer_profiles enable row level security;
alter table public.field_polygons enable row level security;

create policy "profiles are readable" on public.farmer_profiles
for select to anon using (true);

create policy "profiles are writable" on public.farmer_profiles
for insert to anon with check (true);

create policy "profiles are updatable" on public.farmer_profiles
for update to anon using (true) with check (true);

create policy "polygons are readable" on public.field_polygons
for select to anon using (true);

create policy "polygons are writable" on public.field_polygons
for insert to anon with check (true);
